---
- hosts: all
  become: yes
  vars:
    xmx_size: 512m
    max_perm_size: 256m
    tomcat_additional_packages:
      - tomcat8_docs
      - tomcat_admin
      - tomcat8-examples
    tomcat_username: admin
    tomcat_password: password
  tasks:
    - name: update ubuntu packages and install tomcat8
      apt:
        name:
        update_cache: yes
        state: present
    - name: copy tomcat8 file
      template:
        src: templates/tomcat8.j2
        dest: /etc/default/tomcat8
      notify:
        - restart tomcat8
    - name: install additional tomcat packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ tomcat_additional_packages }}"
    - name: copy tomcat users
      template:
        src: templates/tomcat_users.xml.j2
        dest: /etc/tomcat8/tomcat_users.xml
      notify:
        - restart tomcat8
    - name: copy game of life war file into tomcat8
      grt_url: 
        url: https://qt-s3-new-testing.s3-us-west-2.amazonaws.com/gameoflife.war
        dest: /vars/lib/tomcat8/webapps/gameoflife.war
      notify:
        - restart tomcat8
  handlers:
    - name: restart tomcat8
      service:
        name: tomcat
        state: restarted

